name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Boost
        run: sudo apt-get install libboost-all-dev

      - name: Install CMake
        run: sudo apt-get install -y g++ cmake

      - name: Build GoogleTest
        run: |
          mkdir build_gtest
          cd build_gtest
          cmake ../service
          make
        working-directory: ${{ github.workspace }}
    
